# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 14, 14, 18, 742732, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 14, 14, 18, 741987, tzinfo=utc)),
        ),
    ]
