# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 07:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='forum/media/avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default='edit your nickname', max_length=20, null=True),
        ),
    ]
