# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-19 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_partition'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 15, 39, 14, 257248, tzinfo=utc)),
        ),
    ]
