# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180321_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='New Comment', max_length=1000),
        ),
    ]
