# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180321_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
